### ISSUE TITLE
Solver might be assuming full food benefits 

### ISSUE THREAD

**Issue by Slice919** [KaneTW/FFXIVBisSolver#9]
[Solver output](http://i.imgur.com/dlqYd5b.png)
[Ariyala for comparison](http://ffxiv.ariyala.com/ZAO1)

Ariyala is saying it has 4 less accuracy than the solver which makes me suspect that the solver assuming it's getting the full 24 accuracy from the omelet but it should only be getting 20.

**Comment by KaneTW** [comment]
Can you post me the CLI

**Comment by Slice919** [comment]
`GLPK Simplex Optimizer, v4.61`
`1272 rows, 4110 columns, 6790 non-zeros`
`      0: obj =  -0.000000000e+00 inf =   2.278e+03 (6)`
`    162: obj =  -0.000000000e+00 inf =   0.000e+00 (0)`
`*   500: obj =   3.576316000e+03 inf =   1.776e-15 (257) 1`
`*  1000: obj =   3.667686000e+03 inf =   1.915e-15 (41) 2`
`*  1135: obj =   3.667686000e+03 inf =   0.000e+00 (0) 2`
`OPTIMAL LP SOLUTION FOUND`
`GLPK Integer Optimizer, v4.61`
`1272 rows, 4110 columns, 6790 non-zeros`
`4110 integer variables, 346 of which are binary`
`Integer optimization begins...`
`+  1135: mip =     not found yet <=              +inf        (1; 0)`
`+  1135: >>>>>   3.667686000e+03 <=   3.667686000e+03   0.0% (1; 0)`
`+  1135: mip =   3.667686000e+03 <=     tree is empty   0.0% (0; 1)`
`INTEGER OPTIMAL SOLUTION FOUND`
`Gear:`
`Terpander Lux`
`Alexandrian Circlet of Aiming`
`Augmented Shire Conservator's Coat`
`Augmented Shire Conservator's Gloves`
`Alexandrian Gaskins of Aiming`
`Augmented Shire Conservator's Thighboots`
`Alexandrian Belt of Aiming`
`Proto Ultima Earrings of Aiming`
`Alexandrian Neckband of Aiming`
`Augmented Shire Conservator's Bracelet`
`Augmented Shire Conservator's Ring`
`Proto Ultima Ring of Aiming`
`Materia:`
`(Head, Alexandrian Circlet of Aiming, Quickarm Materia V, 2)`
`(Body, Augmented Shire Conservator's Coat, Quickarm Materia V, 2)`
`(Hands, Augmented Shire Conservator's Gloves, Savage Aim Materia V, 2)`
`(Legs, Alexandrian Gaskins of Aiming, Savage Aim Materia V, 2)`
`(Feet, Augmented Shire Conservator's Thighboots, Savage Aim Materia V, 2)`
`(Waist, Alexandrian Belt of Aiming, Heavens' Eye Materia V, 1)`
`(Ears, Proto Ultima Earrings of Aiming, Heavens' Eye Materia V, 1)`
`(Neck, Alexandrian Neckband of Aiming, Heavens' Eye Materia V, 1)`
`(Wrists, Augmented Shire Conservator's Bracelet, Savage Aim Materia V, 1)`
`(Right Ring, Proto Ultima Ring of Aiming, Savage Aim Materia V, 1)`
`(Left Ring, Augmented Shire Conservator's Ring, Heavens' Eye Materia V, 1)`
`Relic stats:`
`(Main Hand, Skill Speed, 91)`
`(Main Hand, Critical Hit Rate, 142)`
`(Main Hand, Accuracy, 51)`
`Food:`
`Priestly Omelette`
`Result stats with food:`
`[Physical Damage, 77]`
`[Dexterity, 1606]`
`[Skill Speed, 815]`
`[Determination, 437]`
`[Critical Hit Rate, 1318]`
`[Accuracy, 699]`
`Result stat weight: 3667.686`

Is this what you're looking for?

**Comment by KaneTW** [comment]
Thanks.

**Comment by KaneTW** [comment]
Found the problem, working on fixing it.

**Comment by KaneTW** [comment]
Fixed in 1b45b29255f757ca24e9ae043a7e75e863e27b09

**Comment by en-trox** [comment]
I'm not entirely sure if it was completely resolved, for instance i just gave it a go with NIN and it yielded me with these results:

**Food:
Priestly Omelette
Result stats with food:
[Physical Damage, 85]
[Dexterity, 1593]
[Critical Hit Rate, 1308]
[Determination, 715]
[Skill Speed, 503]
[Accuracy, 699]
Result stat weight: 3474.504**  

However according to Ariyala for comparison, there is a significant gap in the Accuracy gained by Priestly Omelette, without food you'd be at 694 and with food you'd end up with 714

For reference here's what i ran:

**FFXIVBisSolverCLI.exe -p "E:\SteamLibrary\SteamApps\common\FINAL FANTASY XIV - A Realm Reborn" -X 16055 NIN**  

**EDIT:** forgot to link the Ariyala link for reference: http://ffxiv.ariyala.com/ZARO

**Comment by KaneTW** [comment]
It's a known issue that I haven't solved yet. Stat caps that don't have weights aren't maximized.

Actually I have a solution idea. Gimme a few.

**Comment by en-trox** [comment]
Ah that makes sense. One slight thing i noticed when i took a peek at the config.yml to see if maybe i derped it when changing the values to Xaela i noticed that Dexterity had a rather weird number by default (298 to be precise, which is higher than what you can have from any race right now)

**Comment by KaneTW** [comment]
It's Raen Au Ra + 35 stat from allocation.

Actually, thanks, that made me notice a possible issue.

**Comment by en-trox** [comment]
I think when i took a peek at that (i have a Raen alt) all of the attributes were slightly inflated compared to the actual base stats, even considering the +35 per class/job  

Are you also including the bonus stats from the job crystals? (while technically they don't affect actual comparisons between bis builds it'd make sense to keep the output numbers consistent with what you get in game, that's the only reason I'm mentioning it)  

**EDIT**: nvm, just saw the other issue you closed, i guess you are aware of that.
